export const categories = [
  {
    id: "education",
    name: "Education Tools",
    description: "Tools for students and teachers",
    icon: "GraduationCap",
    color: "indigo",
    count: 5,
  },
  {
    id: "developers",
    name: "Developer Tools",
    description: "Essential tools for programmers",
    icon: "Code",
    color: "blue",
    count: 6,
  },
  {
    id: "pdf",
    name: "PDF Tools",
    description: "Edit and manipulate PDF files",
    icon: "FileText",
    color: "red",
    count: 5,
  },
  {
    id: "images",
    name: "Image Tools",
    description: "Edit and optimize images",
    icon: "Image",
    color: "green",
    count: 6,
  },
  {
    id: "finance",
    name: "Finance Tools",
    description: "Financial calculators and tools",
    icon: "DollarSign",
    color: "emerald",
    count: 5,
  },
  {
    id: "text",
    name: "Text Tools",
    description: "Text manipulation and analysis",
    icon: "Type",
    color: "yellow",
    count: 4,
  },
  {
    id: "fun",
    name: "Fun Tools",
    description: "Entertaining and useful tools",
    icon: "Smile",
    color: "pink",
    count: 5,
  },
  {
    id: "health",
    name: "Health Tools",
    description: "Health and fitness calculators",
    icon: "Heart",
    color: "rose",
    count: 3,
  },
];
